apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: now49gx7w-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: now49gx7w-python 
  name: now49gx7w-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: now49gx7w-python 
